### PR TITLE
Add Source IP clarification

### PR DESCRIPTION
**Pull request by paigehargrave**

### CODE REVIEW

**Comment by paigehargrave** [comment]
@sleslie23 - PTAL - thank you!

**Comment by paigehargrave** [comment]
@fumingshih - PTAL - thank you!

**Review by fumingshih — APPROVED** [review]
looks good

**Comment by paigehargrave** [comment]
@fumingshih Thank you for the quick response!

**Comment by paigehargrave** [comment]
@valkyrie69 - Can you please take a look and approve - thank you in advance!

**Review by hannanelson — APPROVED** [review]
Looks good. I think Kim will say: don't use may in this context. I'd use might. Line 173

**Comment by paigehargrave** [comment]
@hannanelson Thank you!

**Pull request merged**
