### PR TITLE
SE-13894 Enable IP forwarding

### PR DESCRIPTION
**Pull request by paigehargrave**

### CODE REVIEW

**Comment by jeff-1amstudios** [comment]
I'm not sure this should be in the "Upgrade cluster" page. It feels more related to the networking and port requirements to me

**Comment by paigehargrave** [comment]
Hi @jeff-1amstudios - I believe this information is already on https://docs.mulesoft.com/runtime-fabric/1.4/install-port-reqs - looks like the user missed it. Please let me know what you think is the best way to proceed - thank you! I can just include a link to the entire section in the install-port-reqs topic in the upgrade doc if you agree. For example, in the 'Before You Begin section, add an item that says: "Make sure you have configured the required network settings as provided in https://docs.mulesoft.com/runtime-fabric/1.4/install-port-reqs#required-network-settings."

**Comment by jeff-1amstudios** [comment]
good spotting, you are right! I don't think we need to change the Upgrade page - we already ask users to validate "gravity status" is healthy which tests those sort of requirements already.  I think we can just close this.

**Comment by paigehargrave** [comment]
Closing per Jeff's feedback.

**Pull request closed without merging**
